### ISSUE TITLE
Add to Cart Form encryption error with leading space in Product name

### ISSUE THREAD

**Issue by jsirish** [dynamic/foxystripe#102]
Noticed an error with the encryption in the Add to Cart form.

A product name was entered with a space as the first character - " Wendy's ....". When adding to cart, FoxyCart gave the "name" validation error.

Once the space was removed in the CMS, the validation error disappeared.

Do we need to handle this in the code? And if so what's the best way to do so?

**Comment by muskie9** [comment]
This could probably be a post launch fix. Unit tests will be required with the fixing PR.
