### ISSUE TITLE
Related Products

### ISSUE THREAD

**Issue by jsirish** [dynamic/foxystripe#108]
New feature - from ProductPage, allow user to spec related products. Probably a many many managed via a grid field.

Related products would show on ProductPage template, like spiffs, near the bottom of the page.

**Comment by muskie9** [comment]
Should this be an addon?

**Comment by jsirish** [comment]
Yes, an add on here makes sense to me

On Thursday, January 29, 2015, Nic <notifications@github.com> wrote:

> Should this be an addon?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dynamic/foxystripe/issues/108#issuecomment-72115232>.
>


-- 
*Jason Irish*
CTO

*Dynamic*
Digital(+) Agency
1526 S. 12th St
Sheboygan, WI 53081

JIrish@DynamicDoes.com <JIrish@DynamicDevelop.com>
http://DynamicDoes.com <http://DynamicDevelop.com/>
P: (920) 459-8889

A member of Worldwide Partners Inc. The world's largest owner-operated
agency network.
