### ISSUE TITLE
ProductPage - Image Captions

### ISSUE THREAD

**Issue by jsirish** [dynamic/foxystripe#113]
Allow a caption to be entered for each product image. Would be nice to add a reference to a product option, for example

**Comment by jsirish** [comment]
Looked at this today. Because we have a has_many ProductImage from Product, ProductImage already has a 'Title' field. This could be referenced in the template as a caption.

For PreviewImage, we just reference the Image class. Image does have a Title field as well, which could be leveraged as a caption. It's not super intuitive in the UploadField to set the Title, however.

**Comment by muskie9** [comment]
Should the PreviewImage be included in the flexslider? If the image is used as the preview it may be sized smaller than the flexslider area/overlay. This would also alleviate the need for a a description on the PreviewImage.
