### ISSUE TITLE
OptionGroup validation

### ISSUE THREAD

**Issue by jsirish** [dynamic/foxystripe#156]
Since option groups are shared across many option items, and there tend to be only a handful of OptionGroup records, we need to handle what happens when an OptionGroup is deleted.

If 'Color' were deleted, and multiple products had color selections, it could break the product option drop downs.

We should check, either in validation or onBeforeDelete(), if the OptionGroup currently has any OptionItems, and if so prevent deletion. Only OptionGroups not currently in use could be deleted. Products and their OptionItems would need to be updated to new OptionGroups before the old OptionGroup is deleted.

**Comment by muskie9** [comment]
If the checks move to ```canDelete()``` would this cover it?

```
	public function canDelete($member = null) {
		return (!OptionGroup::get()->filter(array('ProductOptionGroupID' => $this->ID))
			&& Permission::check('Product_CANCRUD'))
			? true
			: false;
	}
```
