### ISSUE TITLE
Do we setup the "None" OptionGroup

### ISSUE THREAD

**Issue by muskie9** [dynamic/FoxyStripe#169]
[Around here](https://github.com/dynamic/FoxyStripe/blob/master/code/objects/OptionGroup.php#L53)

**Comment by jirish** [comment]
I think we should create a default record - will make it easier when cleaning things on onBeforeDelete. However, I don't like "None" - would be weird on a ProductPage.

How about something generic like "Options"? If it ever got used in production, at least it would make some sense as the title for the drop down. Open to other suggestions as well.

**Comment by muskie9** [comment]
Just had an afterthought, if we add a validator for ```ProductOptionGroupID``` we can force that they add a new one per ```OptionItem``` or select an existing one, but the ```OptionItem``` wouldn't save without that relation being set.

**Comment by jirish** [comment]
That's a good idea.

**Comment by muskie9** [comment]
closed via #172
