### ISSUE TITLE
Downloadable Products

### ISSUE THREAD

**Issue by jsirish** [dynamic/foxystripe#17]
Extend Product to create a Downloadable Product page type. 

File downloads will most likely live on FoxyCart, but could offer the option for local hosting. Perhaps through Cloud Assets (if class_exists)

FoxyCart lets you set options for # of downloads, etc. Need to find the correct balance between managing these products in CMS vs. FoxyCart. Might be a good opportunity for API integration.

**Comment by muskie9** [comment]
See comments in #18

**Comment by jsirish** [comment]
Thoughts on downloadables...

FoxyCart doesn't treat these much differently than "regular" products. In fact, I think we could accomplish this today just using FoxyCart categories. FoxyCart also hosts the file by default. If the category shipping options are marked as "downloaded by customer", a download link is included in the receipt.

v1 of this product type could simply be a way to indicate to FC that the product is downloadable (if that's possible in the add to cart form). One of the FC plugins for WP seems to do this.

v2 could be adding options to self-host the downloadable file. FC does charge something for file downloads, maybe bandwidth, so self hosted could be an attractive option. The WP plugins to this as well.

Will need to dig into the docs and API to determine the best way to proceed.
