### ISSUE TITLE
Subscription Products

### ISSUE THREAD

**Issue by jsirish** [dynamic/foxystripe#18]
Extend Product to create a new Subscription product. Examples of this would be any product that uses recurring billing, like a monthly membership.

Should only require slight modifications to the add to cart form. FoxyCart should handle all of the future billing, links to cancel subscription, etc.

**Comment by muskie9** [comment]
Would we do different product types as addons?

**Comment by jsirish** [comment]
To me, subscriptions and downloadables are part of the core module. It's fairly standard functionality for a modern ecommerce site, and could be a good selling point for FS.

I'm assuming it's a rather simple implementation though. If it turns out to be more involved, I think we could consider moving these into an addon.

**Comment by jsirish** [comment]
I've started a branch on my fork for this, [subscriptionWork](https://github.com/jsirish/FoxyStripe/tree/feature/subscriptionWork). Looking to talk through the best approach. 

#### References
*	[docs](https://wiki.foxycart.com/v/2.0/products/subscriptions)
*	[example](http://www.foxycart.com/features/examples#subscription-examples)

The main change in the add to cart form is 'sub_frequency' drop down. Values are time durations (30d, 2w, 3m, 1y). Also seems to support modifiers similar to OptionItems - at least price is shown in the example but imagine code and weight could be useful in some circumstances. 

#### Use Case

Website Hosting

*	Monthly subscription at $30
*	Yearly subscription at 10% discount

#### Setup

Need to think through the best setup:

* SubscribableProduct
  * consider rename of SubscriptionProduct or SubscriptionPage?
  *	has_many SubscriptionItems
  *	extends ProductPage?
  	*	some features of ProductPage don't (likely?) apply:
  		*	Discounts
  		*	ProductOptions
  *	All SubscriptionItems displayed in a single sub_frequency drop down in add to cart form
* SubscriptionItem 
	* has_one SubscribableProduct
  	* extend OptionItem?
    	*	similar in that in can modify price/code/weight
    	* 	need to remove OptionGroup, but would retain relation via inheritence
    	*	concern about OptionItems and SubscriptionItems 'mixing together' in grid fields or model admin
    *	Add field(s) for duration
    	*	FrequencyInt => Int
    	*	FrequencyChar => Varchar(1)
    
I think the approach above works, would need to spend some time removing CMS fields in SubscribableProduct and SubscriptionItem. 

Are there concerns about elegance or bloat with the above approach though?

If so, another option would be to overhaul the Product classes. 

*	ProductBase 
	*	becomes a base class
	*	only those features shared across all product types
*	Physical Product
	*	extends ProductBase
	*	ClassName remains ProductPage for backwards compatability
	*	becomes the new "normal" product
	*	intended to be shipped or picked up
*	Subscribable Product
	*	extends ProductBase
	*	recurring billing
	*	intended to be shipped or downloaded
*	Digital Product
	*	extends ProductBase
	*	intended to be downloaded		
	
Obviously this is a rather large overhaul, but it should keep backwards compatability.

In that spirit, would do something similar for OptionItems - a base class that both OptionItem and SubscriptionItem would extend.
    
#### Other Considerations

**Order History** - Need to udpate parseOrder to handle subscriptions

**Manage subscriptions** - do we need to build a mechanism to edit an existing subscription? Or is it enough to have a cancel link in order history?

FoxyCart sends a receipt on initial order, and each subscription renewal, that contains the cancel link.
