### ISSUE TITLE
Should this be deprecated?

### ISSUE THREAD

**Issue by muskie9** [dynamic/foxystripe#209]
@jsirish 

[FoxyCart::getAPIRequest()](https://github.com/dynamic/foxystripe/blob/master/code/model/FoxyCart.php#L56)

Docblocks show it's for store v1.1. With our thoughts of the new API this will be gone with FoxyCart 2.0.

**Comment by jsirish** [comment]
still works in 2.0 based on my testing. This is what handles the user sync for SSO. Docblock could be updated, but should probably review the docs first.

We'll update all this code when we switch to the new API. I think both API versions will be available for a while, at least I don't remember him giving a sunset date for the current version.

**Comment by muskie9** [comment]
closing until next gen api
