### ISSUE TITLE
Product Search

### ISSUE THREAD

**Issue by muskie9** [dynamic/foxystripe#22]

**Comment by muskie9** [comment]
We'll want to go over how we would want this to function if it's to be different from Site Search.

**Comment by jsirish** [comment]
Definitely.

Initially I see this as a single text field, maybe with auto complete, that searches only ProductPages (vs. site wide). Ideally it would search Title and Content, like site search, but add other fields like Code.

And/Or, it could resemble an advanced search form with multiple fields. Could live in the sidebar of ProductHolder. Similar to what we did in Grid.

**Comment by muskie9** [comment]
Ideally something w/multiple options like Amazon:

![screen shot 2015-01-30 at 9 40 39 am](https://cloud.githubusercontent.com/assets/870751/5978258/2a3055a8-a864-11e4-812c-ddf84c5d0ab6.png)
