### ISSUE TITLE
ENHANCEMENT FoxyStripeStateDropdownField

### ISSUE THREAD

**Issue by muskie9** [dynamic/foxystripe#227]
This field should handle the encryption logic so developers can use it in custom add to cart forms.

**Comment by muskie9** [comment]
Would it make more sense to have a FoxyStripeDropdownField that encrypts any associative array (if cart encryption is turned on) rather than creating a State and Country version?

ref #226

**Comment by muskie9** [comment]
ping @jsirish

**Comment by jsirish** [comment]
I think so. Encrypted text field too, to cover custom implementations?

On Thursday, April 2, 2015, Nic <notifications@github.com> wrote:

> ping @jsirish <https://github.com/jsirish>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dynamic/foxystripe/issues/227#issuecomment-89110911>.
>


-- 

*Jason Irish*
Development Director

*Dynamic*
1526 S. 12th St
Sheboygan, WI 53081

jirish@dynamicagency.com
http://dynamicagency.com
P: (920) 459-8889

**Comment by muskie9** [comment]
I'll have a PR for the dropdown soon, just working on getting some tests setup for it. I'll take a crack at the Text field once the dropdown's wrapped up.

**Comment by muskie9** [comment]
closed via #239
