### ISSUE TITLE
BUG " not being properly escaped for product options

### ISSUE THREAD

**Issue by muskie9** [dynamic/foxystripe#235]
In the case where an option is `Baby: 36" x 50" - In Natural: ($65.00)` with encryption enabled the option file ends up being `<option value="Baby: 36||ef5625e41b3b8d203d4addb6ad19a3a880e05908b261b3529173adf77cc9cc5e" x="" 50"="" -="" in="" natural{p:65.00|w0|c}"="">Baby: 36" x 50" - In Natural: ($65.00)</option>`

I'm guessing this caries over to non-encrypted stores as well.

**Comment by brettflorio** [comment]
@muskie9, if you run into issues with the FoxyCart validation, let me know. We pushed out some improvements to properly handle double quotes in options about a month ago on our end. (Looks like this issue isn't FoxyCart related, but I wanted to let you know that double quotes are something we've recently dealt with, just in case you run into issues there.)

**Comment by muskie9** [comment]
Thanks @brettflorio I tested against our latest tag and the issue was resolved there. I think we patched this probably around the same time, just need to get the particular store up to the latest tag.
