### ISSUE TITLE
FoxyStripeController - determine if order processing functions are missing

### ISSUE THREAD

**Issue by jsirish** [dynamic/foxystripe#345]
https://github.com/dynamic/foxystripe/blob/master/src/Controller/FoxyStripeController.php#L65

vs.

https://github.com/dynamic/foxystripe/blob/2/code/controllers/FoxyStripe_Controller.php#L37

**Comment by jsirish** [comment]
@mak001 we'll need this for the 3 Sheeps upgrade if you could take a look

**Comment by mak001** [comment]
Is it supposed to save the encrypted data now, instead of the decrypted?
It also doesn't save most of the order details like it used to.

**Comment by jsirish** [comment]
I think saving the encrypted data makes sense. We'll just have to make sure to unencrypt it when we use it - there might be a task to parse all existing orders.

re: order details - let's put that logic back in, could be useful for some future features we've discussed. The 3 branch may be a good reference for this.
