### ISSUE TITLE
Add current product to purchase form extension points

### ISSUE THREAD

**Issue by mak001** [dynamic/foxystripe#361]
It would be nicer to include the current product in the parameters passed to `updatePurchaseFormFields` and `updateFoxyStripePurchaseFormFields`.

https://github.com/dynamic/foxystripe/blob/6d9130940a898ed5f92f8050b5572712f42a6eb3/src/Form/FoxyStripePurchaseForm.php#L223

https://github.com/dynamic/foxystripe/blob/6d9130940a898ed5f92f8050b5572712f42a6eb3/src/Form/FoxyStripePurchaseForm.php#L228

**Comment by muskie9** [comment]
This can currently be accomplished via your `Extension` by calling `$this->owner->getProduct()`. That will return the product currently used by the form.
