### ISSUE TITLE
ENHANCEMENT max quantity logic

### ISSUE THREAD

**Issue by mak001** [dynamic/foxystripe#362]
This will allow the user to put a max amount of product of that category in their cart.

- CMS
  - [ ] Max Quantity Toggle
  - [ ] Max Quantity Value (will be 1, but may want this field to be editable)
- Product Form
  - [ ] Via Extension, replace quantity field with hidden field set to max quantity allowed
- FoxyCart Admin
  - [ ] FC script to enforce quantity max [forum post](https://forum.foxycart.com/discussion/11352/dont-allow-user-to-add-items-to-cart-based-on-items-already-in-the-cart)

**Comment by muskie9** [comment]
@mak001 has this been covered in https://github.com/dynamic/foxystripe-inventory?
