### ISSUE TITLE
Single Sign On doesn't seem to be working in 4 branch

### ISSUE THREAD

**Issue by jsirish** [dynamic/foxystripe#365]
I created an account during checkout testing Bemis. It doesn't seem to have created the account in the FoxyStripe website. Could someone take a look?

**Comment by muskie9** [comment]
@mak001 can you take a crack at this. I know there was some shuffling with some things in the controller recently.

**Comment by jsirish** [comment]
Update - it's creating the account, but I'm not able to login. Could be something with hashing the password that comes back from FC

**Comment by mak001** [comment]
The encryption type needs to be specified in the database when creating a member. Right now its being set to `none`. Foxystripe does have different options for encrypting passwords. Should this be more flexible than just setting it to the default?

**Comment by muskie9** [comment]
We should review those available in FS and figure out which one works best. We need to set the type to none as the password sent from FC is already encrypted, so when the user record is created we need to prevent it form encrypting that value again.
