### ISSUE TITLE
gulp and node files - are we using these

### ISSUE THREAD

**Issue by jsirish** [dynamic/foxystripe#375]
Suspect they were added by a module generator:

* gulpfile.js
* package.json
* package-lock.json

If not I'll delete them from the repo

**Comment by korthjp17** [comment]
I think @muskie9 added them when we upgraded the quantity field - lets leave them for now.

**Comment by muskie9** [comment]
The lock file can be removed, but I used part of our workflow to do some JS stuff. As we work through buttoning up the module I'll revisit and adjust as needed.
