### ISSUE TITLE
Add customer review ratings options to products

### ISSUE THREAD

**Issue by muskie9** [dynamic/foxystripe#63]

**Comment by jsirish** [comment]
I like this. I do think it probably should be an add-on module, instead of in the core module.

Would it be fairly simple to extend PageComment, and add something like this?

https://github.com/sheadawson/silverstripe-rateable

**Comment by muskie9** [comment]
I think an addon for this feature is a good idea.

**Comment by jsirish** [comment]
closing as this is well underway here https://github.com/dynamic/foxystripe-reviews
